### ISSUE TITLE
CobaltStrike.rar is flagged as a malicious file

### ISSUE THREAD

**Issue by kevinadhiguna** [ORCA666/cobalt-strike-source-code-leak#1]
Hello, the `CobaltStrike.rar` was flagged as a malicious file in virustotal : 

![image](https://user-images.githubusercontent.com/43397636/124354842-493dd380-dc38-11eb-9cf7-ffd7cf5bead3.png)

Would you mind telling me why did this happen? Thank you.

**Comment by ORCA666** [comment]
hi, idk if you know what are you downloading,
first it is cobalt strike, of course it is getting flagged
second if u think i backdoored the rar file, ur wrong i wont :p
3rd please take a look carefully at the readme , i said turn off the av else it is getting flagged
and last the output of cobaltstrike.rar scan on virus total is literally cobalt strike, what would u expect ?
cobalt strike beacon is detected by most of the antiviruses , if u looking for the real cobalt strike take a look at cobalt wipe repo
the file u are downloading was sent to me via mail from freakboy , if it is backdoored , i got hacked before u
turn of the av and download it again :)

**Comment by kevinadhiguna** [comment]
Thank you for the explanation
